name: bookshelf

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network
      - monitoring_network
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    # environment:
    #   PG_DB_URL: postgres://admin:password@local_postgres:5432/localdb
    #   LOKI_HOST: http://loki:3200
    #   OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdb
    ports:
      - 5432:5432
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d localdb']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app_network:
    name: app_network
  monitoring_network:
    name: monitoring_network
