services:
  loki:
    image: grafana/loki:2.9.0
    container_name: monitoring_loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3200:3100
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki_data:/data/loki
    user: '10001:10001' # Use Loki's default user
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
    networks:
      - monitoring_network

  tempo:
    image: grafana/tempo:2.3.0
    container_name: monitoring_tempo
    command: ['-config.file=/etc/tempo/tempo.yaml']
    ports:
      - 3300:3200 # tempo
    volumes:
      - ./monitoring/tempo:/etc/tempo
      - tempo_data:/tmp/tempo
    networks:
      - monitoring_network

  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    container_name: monitoring_otel_collector
    command: ['--config=/etc/otel-collector/config.yaml']
    volumes:
      - ./monitoring/otel-collector:/etc/otel-collector
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 8888:8888 # metrics
      - 8889:8889 # prometheus metrics
    networks:
      - monitoring_network
    depends_on:
      - tempo

volumes:
  loki_data:
  tempo_data:

networks:
  monitoring_network:
    external: true
