{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Request rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Increase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(http_requests_total{path!~\"/favicon.ico|/metrics\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency of routes in use",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum[$__rate_interval]) * 1000 > 0) / rate(http_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Errors by Endpoint",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(route) (increase(http_errors_total[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_requests_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(route) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum[5m]) > 0) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}