global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "service"
    static_configs:
      - targets: ["host.docker.internal:3000", "api:3000"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

  # - job_name: "docker"
  #   docker_sd_configs:
  #     - host: "unix:///var/run/docker.sock"
  #   relabel_configs:
  #     - source_labels: ["__meta_docker_container_name"]
  #       regex: "/(.*)"
  #       target_label: "container"
  #     - source_labels: ["__meta_docker_container_port_number"]
  #       target_label: "__metrics_path__"
  #       replacement: "/metrics"
