apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3200
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID['\"]?:\\s?['\"]?(\\w+)['\"]?"
          name: TraceID
          url: $${__value.raw}
    editable: false
    isDefault: false
